name: CI
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: '16.x'

      - run: yarn install
      - run: yarn lint

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && (github.ref == 'refs/heads/develop')
  #   env:
  #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #     HEROKU_LOGIN: ${{ secrets.HEROKU_LOGIN }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.4.2

  #     # - name: Set Development Environment
  #     #   if: github.ref == 'refs/heads/develop'
  #     #   env:
  #     #     ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  #     #   run: echo "::set-env name=ENVIRONMENT::developmen"

  #     # - name: Set Production Environment
  #     #   if: github.ref == 'refs/heads/main'
  #     #   env:
  #     #     ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  #     #   run: echo "::set-env name=ENVIRONMENT::production"

  #     - run: |
  #         git fetch --prune --unshallow

  #     - name: Push to Heroku Storybook
  #       if: github.ref == 'refs/heads/develop'
  #       env:
  #         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  #       run: |
  #         cat > ~/.netrc << EOF
  #                   machine api.heroku.com
  #                     login $HEROKU_LOGIN
  #                     password $HEROKU_API_KEY
  #                   machine git.heroku.com
  #                     login $HEROKU_LOGIN
  #                     password $HEROKU_API_KEY
  #         EOF
  #         git push --force https://git.heroku.com/gamecore-frontend-story.git HEAD:master

  #     - name: Push to Heroku
  #       if: github.ref == 'refs/heads/develop'
  #       run: |
  #         cat > ~/.netrc << EOF
  #                   machine api.heroku.com
  #                     login $HEROKU_LOGIN
  #                     password $HEROKU_API_KEY
  #                   machine git.heroku.com
  #                     login $HEROKU_LOGIN
  #                     password $HEROKU_API_KEY
  #         EOF
  #         git push --force https://git.heroku.com/gamecore-frontend.git HEAD:master
